# Generated by Django 5.1.7 on 2025-06-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_published_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
